server:
  port: 8080
  servlet:
    context-path: /device-manager
spring:
  application:
    name: device-manager
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      platform: h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:device_manager;MODE=MySQL;DATABASE_TO_LOWER=true
    username: root
    password: 
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
