
server:
  port: ${device_port:8080}
  servlet:
    context-path: /device-manager
spring:
  application:
    name: device-manager
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${database_id:127.0.0.1}:${database_port:3306}/${database_name:device_manager}?createDatabaseIfNotExist=true
    username: ${database_user:root}
    password: ${database_password:root}
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher 